version: "3.8"

services:
  weather-streamer:
    build: .
    container_name: weather_streamer
    pull_policy: build
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_CONSUME_TOPIC=${KAFKA_CONSUME_TOPIC}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
      - KAFKA_CONSUMER_GROUP=${KAFKA_CONSUMER_GROUP}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    command: uvicorn main:app --host 0.0.0.0 --port 8012
    ports:
      - "8012:8012"
    networks:
      data-station-network:
        ipv4_address: 172.20.14.84
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: weather_redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      data-station-network:

volumes:
  redis_data:

networks:
  data-station-network:
    external: true
